"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var jsx_runtime_1 = require("react/jsx-runtime");
require("../styles/images.scss");
var tennis_racket_png_1 = __importDefault(require("../assets/tennis-racket.png"));
var tennis_balls_png_1 = __importDefault(require("../assets/tennis-balls.png"));
var roger_federer_png_1 = __importDefault(require("../assets/roger-federer.png"));
function Images() {
    return ((0, jsx_runtime_1.jsx)(jsx_runtime_1.Fragment, { children: (0, jsx_runtime_1.jsxs)("div", { className: "images", children: [(0, jsx_runtime_1.jsx)("div", { className: "images-container", children: (0, jsx_runtime_1.jsx)("h1", { className: "images-container-title", children: "Bilder" }) }), (0, jsx_runtime_1.jsxs)("div", { className: "images-container", children: [(0, jsx_runtime_1.jsx)("div", { className: "images-container-content", children: (0, jsx_runtime_1.jsx)("p", { className: "images-container-content-text", children: "Tennis ist ein faszinierender Sport, der sowohl Geschicklichkeit als auch Ausdauer erfordert. Zwei Spieler stehen sich auf einem rechteckigen Spielfeld gegen\u00FCber, das in der Mitte durch ein Netz geteilt ist. Mit einem Schl\u00E4ger versuchen sie, den Ball \u00FCber das Netz zu spielen und dabei Punkte zu erzielen. Jedes Match besteht aus S\u00E4tzen, die wiederum aus Spielen bestehen. Der Sport erfordert schnelle Reflexe, pr\u00E4zise Schl\u00E4ge und eine strategische Herangehensweise, um den Gegner zu \u00FCberlisten." }) }), (0, jsx_runtime_1.jsx)("div", { className: "images-container-content", children: (0, jsx_runtime_1.jsx)("img", { src: tennis_racket_png_1.default, className: "images-container-content-image" }) }), (0, jsx_runtime_1.jsx)("div", { className: "images-container-content", children: (0, jsx_runtime_1.jsx)("p", { className: "images-container-content-text", children: "Tennis hat eine reiche Geschichte und hat sich im Laufe der Jahre zu einem weltweit beliebten Sport entwickelt. Urspr\u00FCnglich im 19. Jahrhundert in England entstanden, hat es seinen Weg in L\u00E4nder auf der ganzen Welt gefunden und zieht Millionen von Fans und Spielern an. Neben den professionellen Turnieren gibt es auch zahlreiche Amateurligen und Clubs, die das Spiel f\u00F6rdern und eine Gemeinschaft von Tennisbegeisterten zusammenbringen." }) }), (0, jsx_runtime_1.jsx)("div", { className: "images-container-content", children: (0, jsx_runtime_1.jsx)("img", { src: tennis_balls_png_1.default, className: "images-container-content-image" }) }), (0, jsx_runtime_1.jsx)("div", { className: "images-container-content", children: (0, jsx_runtime_1.jsx)("p", { className: "images-container-content-text", children: "Neben den physischen Vorteilen bietet Tennis auch zahlreiche mentale und soziale Vorteile. Es f\u00F6rdert die Konzentration, verbessert die Hand-Auge-Koordination und st\u00E4rkt die Muskulatur. Dar\u00FCber hinaus lehrt es Spieler Teamarbeit, Fairplay und Durchhalteverm\u00F6gen. Die Mischung aus Technik, Taktik und k\u00F6rperlicher Fitness macht Tennis zu einem anspruchsvollen, aber auch lohnenden Sport f\u00FCr Menschen jeden Alters." }) }), (0, jsx_runtime_1.jsx)("div", { className: "images-container-content", children: (0, jsx_runtime_1.jsx)("img", { src: roger_federer_png_1.default, className: "images-container-content-image" }) })] })] }) }));
}
exports.default = Images;
